group 'com.rioapp.demo.imeiplugin.imei_plugin'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        // 华为官方广告标识服务SDK
        maven { url 'https://developer.huawei.com/repo' }
        // 荣耀官方广告标识服务SDK
        maven { url 'https://developer.hihonor.com/repo' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        // 华为官方广告标识服务SDK
        maven { url 'https://developer.huawei.com/repo' }
        // 荣耀官方广告标识服务SDK
        maven { url 'https://developer.hihonor.com/repo' }
    }
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "com.rioapp.demo.imeiplugin.imei_plugin"
    }
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 19
    }

    dependencies {
        implementation 'com.github.gzu-liyujiang:Android_CN_OAID:4.2.17'
        runtimeOnly "com.huawei.hms:ads-identifier:3.4.62.300"
        runtimeOnly "com.hihonor.mcs:ads-identifier:1.0.2.301"
    }
}
